# Generated by Django 3.2.5 on 2022-02-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_doctor',
            new_name='doctor_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_labTechnician',
            new_name='patient_status',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_receptionist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_time',
        ),
    ]
